#!/usr/bin/env ruby
# frozen_string_literal: true

repo_lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(repo_lib) if File.directory?(repo_lib) && !$LOAD_PATH.include?(repo_lib)

require "kettle/test/version"

script_basename = File.basename(__FILE__)
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Kettle::Test::Version::VERSION
  exit(0)
end
if ARGV.delete("--verbose")
  puts "== #{script_basename} v#{Kettle::Test::Version::VERSION} =="
  $stdout.flush
end

bin_dir = File.expand_path(__dir__)
bash_script = File.join(bin_dir, "kettle-test.sh")

exec(bash_script, *ARGV)
